apiVersion : apps/v1
kind: Deployment
metadata:
  name: "gustavaksteslax-d2f5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gustavaksteslax-d2f5"
  template:
    metadata:
      labels:
        app: "gustavaksteslax-d2f5"
    spec:
      containers:
        - name: "gustavaksteslax-d2f5"
          image: "gustavacr01.azurecr.io/gustavaksteslax"
          ports:
          - containerPort: 80