apiVersion: v1
kind: Service
metadata:
    name: "gustavaksteslax-d2f5"
    labels:
        app: "gustavaksteslax-d2f5"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "gustavaksteslax-d2f5"